---
output:
  word_document:
    reference_docx: "~/HeadRs/rmd_templates/style-guide-arial-11.docx"
bibliography: "`r path.expand('~/Box Sync/papers/EnvEpi.bib')`"
csl: "`r path.expand('~/HeadRs/csl/asa.csl')`"
---

```{r, include=FALSE, eval=F}
knitr::opts_chunk$set(echo=F, results = 'asis')
library(bibtex)
biblio <- bibtex::read.bib('~/Box Sync/papers/EnvEpi.bib')
```

Non-Hodgkin Lymphoma (NHL) is the seventh most common cancer type in the United States and has garnered substantial research attention because its incidence in the United States doubled between 1973 and 1994, before plateauing at around 19 per 100,000 persons per year [@seer_1994;@Ekstrom-Smedby_2006]. The strongest known risk factor of NHL is immunosuppression, both congenital and acquired [@Filipovich_1992;@Chiu_2015]. Modulation of immune function contributes to the pathogenesis of NHL directly by perturbing lymphocyte function or indirectly by reducing immunosurveillance against neoplasms. Immunodeficiency may also interact with infection with Epstein-Barr Virus, resulting in uncontrolled B-cell proliferation [@Oertel_2002]. Acquired immunodeficiency through infection with human immunodeficiency virus (HIV) can lead to genetic lesions and dysregulation while increasing vulnerability to infection by other oncogenic agents [@Grulich_1999;@Alexander_2007]. However, since immunodeficiency and infection with HIV are rare, they cannot fully explain the historic rise or present burden of NHL [@Shiels_2013]. Since the rise in NHL incidence coincided with a period of rapid and extensive chemicalization in industry, agriculture and warfare, there has been stronger interest in the environmental and occupational epidemiology on NHL [@Nelson_2005;@Romero_2021].

Pesticide exposure in agricultural occupational settings was a common target of NHL research in recent decades. A meta-analysis of 44 articles published between 1980 and 2014 found statistically significant associations between NHL and exposure to pesticides of several classes including carbamate, organophosporus, triazine, and organochlorine [@Schinasi_2014]. Occupations associated with NHL are not limited to the agricultural sector, however. Metal processors, health workers, salespeople, machinists, and electricians have all been identified as occupational groups with higher risk of NLH [@Fritschi_2005a; @Mester_2006; @Ekstrom-Smedby_2006]. Studies contrasting occupational groups to the general population are vulnerable to exposure misclassification of the true causal agent. When different causal agents contribute to overall NHL risk by their effect on particular subtypes of NHL, their etiologic role may be obscured in analyses not stratified by subtype. Large multicenter studies including EPILYMPH and INTERLYMPH seek to disentangle effect heterogeneity across NHL subtypes, but are limited by the lack of quantitative time-varying exposure information [@Besson_2006;@t-Mannetje_2008;@Morton_2014].

Measures of time-varying exposure are essential to statistical adjustment for forms of time-varying confounding affected by past exposure such as the healthy worker survivor effect (HWSE). The HWSE is the dynamic selection process by which healthier individuals remain at work, where they accumulate more occupational exposure, and less healthy individuals leave work [@Arrighi_1994]. Standard analyses of occupational cohorts affected by the HWSE result in a downward bias on the exposure-outcome associations of interest, as less healthy workers typically accrue less exposure than healthier workers.

Metalworking fluids (MWF), an important class of occupational exposures, are complex mixtures of oils and chemicals used to lubricate and cool metal during manufacturing processes. During use, MWFs aerosolize and present a potential health hazard to exposed workers. The type of MWF applied depends in part on the particular metalworking operation. Straight MWF, the oldest class of MWF, is comprised mostly of mineral oils, which were classified as carcinogenic by the International Agency for Research on Cancer (IARC) in 1973, citing studies of occupational exposures among workers in oil, textile, and metal industries [@IARC_1973]. The combination of health concerns, the high cost of oil in the 1970s, and the introduction of performance-enhancing water-soluble chemical additives led to the gradual replacement of straight MWF with water-based soluble and synthetic MWFs for many, but not all operations [@Childers_2005].

Although water-based MWF contain little to no mineral oil, they contain a richer cocktail of additives including chromates, cycloalkanes, phenols, organochlorines, nitrites, sulfonates, and triazines: classes of chemicals with known or plausible carcinogenicity [@IARC_1987;@IARC_2014;@IARC_2017]. The elimination of particular etiologic agents often leads to their replacement with other potentially hazardous chemical compounds [@Kassotis_2020;@Maertens_2021]. Hence, limits on entire classes of exposures grouped by functional use may result in stronger, more lasting protections for worker health than limits on particular etiologic agents because they will remain in place even as the composition and formulation of complex occupational exposures change [@Maertens_2021]. More than 20 years after the IARC classification of mineral oils as carcinogenic, the National Institute for Occupational Safety and Health (NIOSH) concluded that there exists substantial evidence linking all MWF exposure to several different cancers. However, the NIOSH recommended exposure limit of 0.5 mg/m^3^ for total particulate matter derived from any type of MWF was intended to reduce respiratory disorders and not cancer [@niosh_1998;@Mirer_2003].

Here, we assess the effect of hypothetical MWF exposure limits on NHL cumulative incidence (which we will refer to as risk) from 1985 to 2005 in the United Auto Workers-General Motors (UAW-GM) Occupational Cohort Study. The large size of the study population and rich time-varying, quantitative MWF exposure data provide an opportunity to study this relatively rare cancer and evaluate realistic interventions on MWF exposure in a longitudinal cohort setting. A recent study of cancer incidence in this iconic occupational cohort found a monotonic association between NHL and exposure to soluble MWF [@Colbeth_2022]. This association was based on standard Cox proportional hazards regression, a method vulnerable to bias due to confounding by time-varying factors affected by past exposure. We therefore explore this association using an estimator capable of adjusting for time-varying confounding and censoring affected by past exposure: the hazard-extended iterative conditional expectation (ICE) parametric g-formula. Like other causal estimators in statistics, the hazard-extended ICE g-formula yields marginal effect estimates of hypothetical interventions, which are more compatible with a population health framework than conditional measures.

The g-formula is a well-known result in causal inference for the identification of causal effects in the presence of time-varying confounding affected by past exposure [@Robins_1986]. Standard representations of the g-formula include (1) a non-iterated expectation over the joint density of covariates, (2) the ICE over time, and (3) an inverse probability weighted expectation. The parametric g-formula is a plug in estimator for the g-formula under its first, non-iterative, representation. It involves the parametric modeling of the full joint distribution of the outcome, exposure, and covariates under study for each time point [@Taubman_2009;@Young_2014]. Counterfactual quantities under hypothetical interventions of interest are computed from Monte Carlo samples from distributions implied by the fitted parametric models. In longitudinal settings, this approach often requires specifying and fitting large number of models in order to satisfy the exchangeability assumptions necessary for causal identification.
<!-- Since applications of the parametric g-formula are often context-laden, there are no unified guidelines for model specification. -->

When researchers are not wholly comfortable with the full set of parametric assumptions required by the parametric g-formula, the ICE g-formula may be preferred. Parametric estimators using the ICE representation of the g-formula require modeling only the conditional outcome distributions, so they require fewer parametric assumptions than non-iterative parametric g-formula estimators. Counterfactual outcome estimates over the follow-up period are computed from interval-specific conditional estimates by applying the tower rule of expectation. Under the assumptions of conditional exchangeability at all time points, positivity, counterfactual consistency, and correct model specification, the hazard-extended parametric g-formula yields unbiased estimates of counterfactual risk with greater statistical efficiency than both propensity score-based estimators and the classical ICE g-formula.