---
output:
  word_document:
    reference_docx: "~/HeadRs/rmd_templates/style-guide-arial-11.docx"
bibliography: "`r path.expand('~/Box Sync/papers/EnvEpi.bib')`"
csl: "`r path.expand('~/HeadRs/csl/asa.csl')`"
---

```{r, include=FALSE, eval=F}
knitr::opts_chunk$set(echo=F, results = 'asis')
library(bibtex)
biblio <- bibtex::read.bib('~/Box Sync/papers/EnvEpi.bib')
```

# Methods

We estimated NHL risk from 1985 to 2005 under hypothetical limits on average annual exposure to soluble MWF by applying the novel hazard-extended iterative conditional expectation (ICE) parametric g-formula estimator [@Wen_2020]. We leveraged time-varying quantitative MWF exposure data in tandem with employment records to adjust for the HWSE. First, we estimated the expected number of NHL cases per 1000 workers that we would observe if there were no competing risks. We contrasted  this counterfactual risk to that when in addition, the hypothetical exposure limits of 0.5, 0.25, and 0.05 mg/m^3^ were enforced for soluble MWF over workers' entire working lifetimes. These hypothetical limits are static interventions because they do not consider other covariates or exposures. However, since workers were often exposed to multiple types of MWF, both daily and cumulatively, we also evaluated the effect of limiting total MWF exposure to those hypothetical limits by intervening only on exposure to soluble MWF. These interventions, which take into consideration exposure to MWF of other types, are dynamic interventions on exposure to soluble MWF. All of the hypothetical interventions we evaluate are stochastic interventions rather than deterministic interventions because post-intervention exposures take on a range of values.

## Study population

The UAW-GM cohort includes all hourly workers at three automobile manufacturing plants in Michigan who had worked at least 3 years by 1985. Past papers provide detailed descriptions of the cohort [@Eisen_1992;@Eisen_2001]. The present study population (N = 34,738) was restricted to the autoworkers who were at work in 1941 or not yet hired, missing no more than half of their employment history, and still alive at the start of follow-up. Autoworkers in the study population were followed for NHL incidence from January 1, 1985 until NHL diagnosis, death, 10 years after the end of employment records, or upon reaching the oldest observed age at death (108 years), whichever came earlier.

## Outcome and covariates

We identified incident cancers in the UAW-GM Cohort that occurred between 1985 and 2004 by linkage to the Michigan Cancer Registry (MCR). Workers at Plants 1 and 2, located in the greater Detroit metropolitan area, were also linked to the Detroit Regional Registry of the Surveillance, Epidemiology, and End Results (SEER) Program. Cancer types were distinguished using site and histology codes conforming to the International classification of Diseases for Oncology, 3^rd^ edition (ICD-O-3). Non-Hodgkin lymphoma was defined by cancers with any of the following ICD-O-3 Histology codes: 9590-9597, 9670-9671, 9673, 9675, 9678-9680, 9684, 9687-9691, 9695, 9698-9702, 9705, 9708-9709, 9712, 9714-9719, 9724-9729, 9735, 9737-9738, 9811-9818, 9823, 9827, 9837. Details regarding cancer incidence follow-up are described elsewhere [@Colbeth_2022]. Vital status was ascertained from company records and by linkage to Social Security Administration, National Death Index, and state mortality files.

Covariates including year of hire, sex, race, and plant location were obtained from company records. Race was missing for about 16% of the cohort, most commonly among workers hired before 1960 in Plant 2. In analyses, missing race was considered a distinct category.

## Exposure

Company industrial hygienists collected several hundred personal and area samples for total particulate matter (mg/m^3^) composed of MWF over many decades. Research industrial hygienists collected additional air sampling data when the cohort study was launched in the mid 1980s. These data were combined with the historical data to derive quantitative 8-hour time-weighted average exposure estimates to soluble, straight, and synthetic MWFs for each combination of job, department, and plant over time. Workers' time-weighted average annual exposure to each MWF type was determined by combining this job-exposure matrix with employment records, which recorded time-varying job type, department, and plant. For employment records that were at least half complete, gaps in the record were interpolated by carrying forward the last known job type. The exposure assessment is described in detail elsewhere [@Hallock_1994;@Woskie_1994;@Woskie_2003]. Previous analyses of NHL applied exposure lags of 1 to 20 years; we lagged cumulative MWF exposures by 10 years to account for disease latency [@Smith_2007;@Karipidis_2007;@Zhang_2019]. 

## Statistical methods

We applied the hazard-extended ICE parametric g-formula with pooling over treatment history [@Wen_2020] to estimate 20-year counterfactual risk of non-Hodgkin lymphoma. We considered six stochastic interventions on average annual exposure to soluble MWFs after the elimination of censoring/competing risks. We considered hypothetical exposure limits starting with the NIOSH Recommended Exposure Limit (REL) for total particulate mass (PM) from MWFs (0.5 mg/m^3^). Then, we estimated the risk at half the REL (0.25 mg/m^3^), and a tenth of the REL (0.05 mg/m^3^) [@niosh_1998]. The first three interventions were static interventions which enforced these hypothetical limits on average annual exposure to soluble MWF. The remaining three interventions were dynamic interventions that reduced average annual exposure to soluble MWF with the goal of enforcing the hypothetical limits for total exposure to MWF, regardless of type. If those limits on total average annual exposure were not possible by intervention on exposure to soluble MWF alone, average annual exposure to soluble MWF was reduced to 0. Interventions were applied at hire, before the start of follow-up, through the end of follow-up. Person-years were not intervened upon if the observed average annual exposure was below the hypothetical limit. Figure 1 illustrates the static and dynamic interventions for three person-year examples. Panel A shows the observed levels of exposure to soluble MWF and to MWF of other types. Panel B shows the post-intervention levels of exposure under a static intervention capping exposure to soluble MWF at the hypothetical limit (dotted line). Panel C shows the post-intervention levels under a dynamic intervention reducing exposure to soluble MWF with the goal of capping total MWF exposure at the hypothetical limit. Note that in person-year 3, the observed level of exposure to total MWF (and thus, to soluble MWF) is below the hypothetical limit, so the post-intervention exposure is left at the observed level.

![Figure 1. Observed and post-intervention levels of exposure to soluble MWF and MWF of other types in three example person-years. The white boxes represent exposure to soluble MWF, and the shaded boxes represent exposure to MWF of other types. The horizontal dotted line represents the hypothetical exposure limit.](`r here::here("resources/images", "interventions.png")`){width=6.5in}

The hazard-extended ICE parametric g-formula estimator is an ICE expression of the parametric g-formula estimator further extended to incorporate the predicted hazard of past outcomes [@Wen_2020]. The classical ICE g-formula estimator is algebraically equivalent to the noniterative conditional expectation (NICE) g-formula estimator, which typically involves computing covariate-standardized estimates sequentially, starting at the index time, by specifying parametric models for the joint distribution of the confounders, exposures, and outcomes at each time point [@Taubman_2009]. In contrast, ICE g-formula estimators avoid the need for modeling the entire joint distribution of observed variables and only require outcome models for each time point. Counterfactual outcome estimates over the follow-up period are computed from interval-specific conditional estimates by applying the tower rule of expectation. Under the assumptions of conditional exchangeability at all time points, positivity, counterfactual consistency, and correct model specification, the hazard-extended parametric g-formula yields unbiased estimates of counterfactual risk with greater statistical efficiency than both propensity score-based estimators and the classical ICE g-formula.

Our implementation of the hazard-extended ICE parametric g-formula involved a series of model-based standardization steps using logistic regression. Post-intervention estimates of the discrete hazard of NHL given all exposures and covariates were combined iteratively from the end of follow-up to the start. In each iteration, predicted discrete hazards were standardized over post-intervention exposure and covariate histories before combining with discrete hazards from the previous iteration. This iterative process resulted in sequentially standardized estimates of NHL risk over the entire follow-up period. Averaging over the baseline distribution of covariates yielded the counterfactual risk estimate of NHL when the intervention of interest was enforced for the entire study population.

We split the 20-year follow-up period into eight time periods; the first two periods spanned four years each, and the remaining six periods spanned two years each. The first two periods are longer in length to account for the smaller number of cases in those years. Post-intervention exposure and exposure history were summarized as cumulative exposure. We modeled discrete hazards by fitting a pooled logistic regression for NHL over at-risk person-periods given cumulative exposure to straight, soluble, and synthetic MWFs, employment status, cumulative time off, year of hire, sex (male/female), race (Black/white/unknown), and plant (Plant 1/Plant 2/Plant 3). Cumulative exposure to MWFs, employment status, and cumulative time off were lagged 10 years. All continuous variables were represented as categorical variables with cut points determined by the tertiles of nonzero values among NHL cases. During the iterative combination of discrete hazards, we performed model-based standardization over baseline covariates and the complete set of time-varying covariate histories.

We estimated risk under the observed distribution of soluble MWF exposure (natural course) and under the six interventions. We contrasted the risk under intervention to that under the natural course by computing relative risks. Confidence intervals were computed using the nonparametric bootstrap with 1000 samples and centering on the estimate computed from observed data.

<!-- GITHUB? -->