---
output:
  word_document:
    reference_docx: "~/HeadRs/rmd_templates/style-guide-arial-11.docx"
bibliography: "`r path.expand('~/Box Sync/papers/EnvEpi.bib')`"
csl: "`r path.expand('~/HeadRs/csl/ama.csl')`"
---

```{r, include=FALSE, eval=F}
knitr::opts_chunk$set(echo = F, results = 'asis',
											tab.cap.tnd = 1)
if (!'tidyr' %in% loadedNamespaces()) {library(tidyverse)}
library(flextable)
```

# Discussion

We estimated counterfactual 20-year risks of NHL from 1985 to 2005 in the UAW-GM  Cohort Study under different hypothetical interventions targeting exposure to soluble MWFs using the hazard-extended ICE parametric g-formula. We found a monotonic dose-dependent relationship with lower risk estimates arising from stronger limits. Contrasts in estimated NHL risk were statistically significant under the strongest static intervention, which limited soluble MWF exposure to 0.05 mg/m^3^, and the two dynamic interventions, which reduced exposure so that total MWF exposure would be capped at 0.5 or 0.25 mg/m^3^, if possible. The dynamic interventions, which take into consideration exposure to the other MWF types, may be more efficient at reducing risk of NHL than the static interventions, which ignore exposure to the other MWF types.

Colbeth et al. first reported an association between NHL and MWF exposure in this cohort in their standard survival analyses, which investigated associations between MWF exposure and several cancer incidence outcomes [@Colbeth_2022]. We verified and further examined this association in an approach capable of adjusting for time-varying confounding possibly affected by past exposure. The present approach also yielded marginal rather than conditional estimates of effect while evaluating realistic interventions, and is thus more compatible with a population health framework. Under the assumptions of conditional exchangeability, positivity, consistency, and correct model specification, our estimates are unbiased for the true counterfactual risk under the hypothetical interventions.

Conditional exchangeability means that for all time points, there is no confounding of the relationship between exposure/censoring and NHL status at all future time points given the observed past, including past exposure and covariates. A major threat to conditional exchangeability in longitudinal occupational studies is the HWSE. We limit potential bias due to the HWSE by conditioning on all past cumulative exposure, employment status, and cumulative time off at each time point. Cumulative time off and employment status are reasonable mediators of the causal paths linking past health to future exposure and health, but may not be sufficient to fully adjust for the HWSE. Declines in a worker's health may lead to reductions in work-related exposure without affecting employment status or time off work [@Garcia_2017]. We expect the absence of good time-varying measures of worker health over the life course to result in bias toward the null.

Positivity refers to the need for adequate variation in future exposure among strata formed by observed covariate and intervention-compliant exposure histories. Even under conditional exchangeability, where exposures within these strata may be considered the result of experimental assignment, expected counterfactual outcomes under different exposures may not be estimable if there is sparsity in the observed distribution of exposures [@Maldonado_2002]. We investigated static and dynamic stochastic interventions on soluble MWF exposure which intervened only when average annual exposure exceeded the hypothetical limit under consideration. Hence, our parameters of interest achieve positivity more easily than those for deterministic interventions e.g. setting all to exposed versus unexposed. Nonetheless, violations in positivity were still of concern due to the high dimensionality of covariates, as in common in longitudinal settings. We addressed sparsity by summarizing the 20 years of follow-up over a coarser timescale with only 8 follow-up periods and by representing covariates using fewer categories. Coarsening limits the comprehensiveness of confounding control, but improves positivity. In practice, causal inference using observational data must always balance positivity, covariate adjustment, and model specification [@Petersen_2012]. When estimating causal effects using estimators that do not require exposure modeling, as is the case with g-formula methods, concerns over potential bias due to practical violations in positivity may be relaxed if correct model specification is attained.

The consistency assumption, also known as the no-multiple-versions-of-treatment or stable unit treatment value assumption, is that counterfactual outcomes under each possible exposure value take on a unique value [@Cole_2009;@VanderWeele_2013]. This assumption would be violated if there were multiple versions of treatment causally associated with different outcomes. This basic notion of consistency is violated in our analysis because our exposure of interest is a complex mixture of diverse components with substantial variation over time due to changes in formulation and due to the natural physical, chemical, and biological changes in the MWF over the course of its use [@Howell_2006]. However, causal effects estimates under violations in the consistency assumption are still valid and unbiased if there is adequate adjustment for confounders of the exposure-version relationship [@VanderWeele_2013]. This may be thought of as conditional consistency within strata, in which there is only one version of treatment. Our analysis indexed time periods over calendar time and adjusted for age, year of hire, and plant. In this way, we limited potential for bias due to variation in MWF composition.

Correct model specification is a standard assumption in all analyses. The estimator we applied offers greater statistical efficiency than the classical ICE parametric g-formula estimator because it leverages greater parametric smoothing. In causal analyses of longitudinal cohort studies, both the hazard-extended and classical ICE parametric g-formula estimators are less common than the non-iterative expression (NICE) of the parametric g-formula [@Keil_2014]. However, a major limitation of the NICE g-formula is the g-null paradox: the guaranteed misspecification of parametric models resulting in the false rejection of the null hypothesis when the null is true and there is time-varying confounding affected by past exposure [@Naimi_2015;@McGrath_2022]. As with all ICE g-formula estimators, the estimator we applied is not subject to the g-null paradox. Furthermore, simulation studies show that the variance of the hazard-extended ICE parametric g-formula is similar to that of the NICE parametric g-formula, so we expect the former to be no less conservative than the latter [@Wen_2020].

<!-- In the last several decades, there have been substantial changes in the formulation of MWF, including the exclusion of nitrogenous compounds and the use of highly-refined mineral oils. The recent establishment of the Ecolabel for lubricants in the European Union reflects the shift toward prioritizing sustainability and health in the design and production of MWF and other lubricants [@EU_2018;@Skerlos_2008]. However, water-based MWF that satisfy Ecolabel criteria are nonetheless susceptible to the accumulation of dirt, metals, microbes, products of microbial metabolism, and unemulsified oil. These contaminants and their control strategies may also induce risks to human health. Furthermore, adoption of this new class of MWF remains limited, as is evidence of their safety. Considering the evolving complexity in MWF composition, epidemiologic investigations remain an invaluable approach for developing evidence-based occupational health policy and estimating their causal effect. -->

Much of the existing epidemiologic literature linking occupational and environmental exposures to NHL risk report findings from case-control studies where exposures are measured crudely as binary indicators of exposure or membership in a particular occupational group [@Cano_2001;@Costantini_2001;@Karunanayake_2008;@t-Mannetje_2016]. Associations between occupations and NHL risk vary considerably, but one study of working men in Kansas and Nebraska found strong associations between NHL risk and occupations involving metalworking and motor vehicles [@Zheng_2002]. Both of these occupations may entail exposure to soluble MWFs, which contain a number of additives of concern for human health and NHL risk in particular. Organic compounds containing phosphorous, chlorine, sulfur, nitrogen, and boron are commonly added to soluble MWF to control microbial growth, improve performance under high heat/pressure, and inhibit corrosion [@Evans_2020]. Organophosphorous compounds include organophosphate pesticides, which have been linked to cancer risk in epidemiologic and animal studies. Some were classified as possibly carcinogenic by the IARC [@IARC_2017]. Studies of occupational exposure to chlorinated solvents and pesticides have also been linked to NHL risk [@Cocco_2008;@Purdue_2011;@Cocco_2013;@Vlaanderen_2013;@Callahan_2018]. In 2014, the International Agency for Research on Cancer classified trichloroethylene, tetrachloroethylene, and other chlorinated agents as Group 1 carcinogens [@IARC_2014]. Chlorinated solvents are commonly used as degreasers in industrial settings, but their use in the plants under study here was uncommon and limited to particular operations [@Shrestha_2016]. The structural characteristics shared by MWF additives and known/suspected carcinogens suggest similarities in molecular function and carcinogenesis.

This study investigated the effect of hypothetical limits on average annual exposure to MWF by comparing the standardized distribution of NHL under various distributions of cumulative exposure induced by applying upper bounds to annual exposure. When average annual exposure did not exceed the hypothetical limit, it was left at the observed level of exposure. We selected these hypothetical limits based on the NIOSH REL of 0.5 mg/m^3^ [@niosh_1998]. Without enforcement of the REL, we still observed average annual exposures below the REL for many person-years. If the REL were enforced in the real world, we would not expect reductions in exposure for these low-exposure person-years. Hence, contrasting the counterfactual scenario where all workers experienced annual exposure at the REL to one where all workers experienced annual exposure at some higher level would result in an overestimate of the expected real-world benefit of REL enforcement. By considering stochastic interventions that result in exposure distributions more similar to what we would expect in the real world, our analysis yielded results that more realistically quantify the effects of policy than those investigating deterministic interventions [@Bembom_2007;@Munoz_2012].

<!-- The interventions we considered are stochastic interventions resulting in post-intervention distributions of exposure that better reflect what we would expect if exposure limits were enforced in the real world. The interventions which ignore exposure to straight and synthetic MWFs are static. The interventions which reduce exposure to soluble MWF by a quantity determined by exposure to other MWF are dynamic. The dynamic stochastic interventions respect the fact that the REL is for total MWF, not just soluble MWF. If an individual experienced a large amount of exposure to straight and synthetic MWF in one year, then their exposure to soluble MWF should be bounded at a lower level so that the sum of their exposure to soluble, straight, and synthetic MWFs is no greater than the hypothetical limit.  -->

Associations between several occupations and risk of NHL have been reported previously, but none evaluated the potential effect of hypothetical limits on occupational exposures [@Ekstrom-Smedby_2006;@Chiu_2015;@t-Mannetje_2016;@Callahan_2018]. We found evidence that exposure to soluble MWF was associated with NHL incidence after adjustment for time-varying confounding affected by prior exposure using the hazard-extended ICE parametric g-formula. Shifting the distribution of cumulative exposure to soluble MWF by limiting average annual exposure resulted in reductions in NHL incidence. Limits on exposure to soluble MWF that take into consideration exposure to straight and synthetic MWFs led to greater reductions NHL incidence while intervening on fewer person-years.